cards:
  - name: Visits & Engagement
    description: >-
      Visits: the total number of conversations in a given temporal window.
      Engagements: of those conversations, those with length one or more.
    type: conversationCounts
    visible: true
    startDate: '2022-01-29T22:00:00.000Z'
    endDate: '2022-03-01T21:59:59.999Z'
    chartType: bar
    valueType: absolute
    includeIntents: null
    excludeIntents: null
    includeActions: null
    excludeActions: null
    conversationLength: 1
    userInitiatedConversations: true
    triggerConversations: true
    selectedSequence: null
    wide: true
    showDenominator: true
    limit: null
    eventFilter: []
    eventFilterOperator: or
    __typename: AnalyticsCard
  - name: Top 10 Intents
    description: null
    type: intentFrequencies
    visible: true
    startDate: '2022-01-29T22:00:00.000Z'
    endDate: '2022-03-01T21:59:59.999Z'
    chartType: table
    valueType: absolute
    includeIntents: null
    excludeIntents:
      - get_started
    includeActions: null
    excludeActions: null
    conversationLength: null
    userInitiatedConversations: null
    triggerConversations: null
    selectedSequence: null
    wide: true
    showDenominator: null
    limit: 10
    eventFilter: null
    eventFilterOperator: null
    __typename: AnalyticsCard
  - name: Top Intents
    description: ''
    type: intentFrequencies
    visible: true
    startDate: '2022-01-29T22:00:00.000Z'
    endDate: '2022-03-01T21:59:59.999Z'
    chartType: bar
    valueType: absolute
    includeIntents:
      - feedback_positive
      - feedback_negative
    excludeIntents: []
    includeActions: null
    excludeActions: null
    conversationLength: null
    userInitiatedConversations: true
    triggerConversations: false
    selectedSequence: null
    wide: null
    showDenominator: null
    limit: null
    eventFilter: null
    eventFilterOperator: null
    __typename: AnalyticsCard
  - name: Conversation Duration
    description: null
    type: conversationDurations
    visible: true
    startDate: '2022-01-29T22:00:00.000Z'
    endDate: '2022-03-01T21:59:59.999Z'
    chartType: bar
    valueType: absolute
    includeIntents: null
    excludeIntents: null
    includeActions: null
    excludeActions: null
    conversationLength: null
    userInitiatedConversations: null
    triggerConversations: null
    selectedSequence: null
    wide: null
    showDenominator: null
    limit: null
    eventFilter: null
    eventFilterOperator: null
    __typename: AnalyticsCard
  - name: Conversation Length
    description: null
    type: conversationLengths
    visible: true
    startDate: '2022-01-29T22:00:00.000Z'
    endDate: '2022-03-01T21:59:59.999Z'
    chartType: bar
    valueType: absolute
    includeIntents: null
    excludeIntents: null
    includeActions: null
    excludeActions: null
    conversationLength: null
    userInitiatedConversations: null
    triggerConversations: null
    selectedSequence: null
    wide: true
    showDenominator: null
    limit: null
    eventFilter: null
    eventFilterOperator: null
    __typename: AnalyticsCard
languages:
  - fi
  - en
  - sv
envs:
  - production
name: Default Dashboard
projectId: adgucwSrxaCaNgaLL
__v: 0
